config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :questions do
    resources :answers
  end


  root 'questions#index'
end

app/models/answer.rb
class Answer < ActiveRecord::Base

  belongs_to :user
  belongs_to :question

  validates :body,
            presence: true,
            length:   {minimum: 3}

  def author
    user.name
  end

end

app/models/question.rb
class Question < ActiveRecord::Base

  belongs_to :user

  validates :body,
            presence: true,
            length:   {minimum: 3}

  def author
    user.name
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :answers

  NAME_FORMAT = /\A[A-Z]/

  validates :name,
            presence: true,
            format:   {with: NAME_FORMAT}

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def user_initials
    name.split.map(&:first).join.upcase
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_question

  def create
    @answer = current_user.answers.new(answer_params) do |answer|
      answer.question = @question
    end

    if @answer.save
      redirect_to @question
    else
      @answers = @question.answers

      render 'questions/show'
    end
  end

  def destroy
    @answer = @question.answers.find(params[:id])

    @answer.destroy

    redirect_to @question
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: :show
  before_action :set_user_question, only: [:edit, :update, :destroy]

  def index
    @questions = Question.all.page(params[:page]).per(10)
  end

  def show
    @answers = @question.answers
    @answer  = @question.answers.new
  end

  def new
    @question = current_user.questions.new
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to @question
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    @question.destroy

    redirect_to questions_path(page: params[:page])
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def set_user_question
    @question = current_user.questions.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:body, :author)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  # TODO: Please check if below is the best solution for modifying devise

  before_filter :configure_permitted_parameters, :only => [:create]

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.slim
tr
  td = answer_counter + 1
  td = answer.body
  td = answer.author
  - if user_signed_in? && (answer.user == current_user)
    td = link_to 'Delete', question_answer_path(answer.question, answer), method: :delete, data: {confirm: 'Are you sure?'}
  - else
    td

app/views/answers/_form.html.slim
= form_for [@question, @answer] do |form|
  - if @answer.errors.any?
    .alert-box.alert
      p : strong Please fix #{pluralize(@question.errors.count, 'error')}:
      ul
        - @answer.errors.full_messages.each do |message|
          li = message

  .row
    .large-12.columns
      .row.collapse
        .small-10.columns = form.text_field :body
        .small-2.columns = form.submit class: 'button postfix'

app/views/layouts/application.html.slim
doctype html
html
  head
    title Segfault
    meta content='width=device-width, initial-scale=1.0' name='viewport'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag 'vendor/modernizr'
    = csrf_meta_tags
  body
    .row
      .large-12.columns
        h1 Segfault
        | Where Question.joins(:answers)
        hr
    .row
      .large-12.columns
        - if user_signed_in?
          =' current_user.email
          ' |
          = link_to 'Sign out', destroy_user_session_path, method: :delete
        - else
          = link_to 'Sign in', new_user_session_path
        hr
    .row
      .large-12.columns
        - if flash.notice
          .alert-box.success = flash[:notice]
        - if flash.alert
          .alert-box.alert = flash[:alert]
        = yield

app/views/questions/_form.html.slim
= form_for @question do |form|
  - if @question.errors.any?
    .alert-box.alert
      p : strong Please fix #{pluralize(@question.errors.count, 'error')}:
      ul
        - @question.errors.full_messages.each do |message|
          li = message

  .row
    .small-2.columns = form.label :body, class: 'right inline'
    .small-10.columns = form.text_field :body
  .row
    .small-2.columns
    .small-10.columns = form.submit class: 'button'

app/views/questions/_question.html.slim
tr
  td = @questions.offset_value + question_counter + 1
  td = question.body
  td = question.author
  td = link_to 'Show', question_path(question)
  - if user_signed_in? && (question.user == current_user)
    td = link_to 'Edit', edit_question_path(question)
    td = link_to 'Delete', question_path(question), method: :delete, data: {confirm: 'Are you sure?'}
  - else
    td
    td

app/views/questions/edit.html.slim
h1.clearfix
  | Edit question
  = link_to 'Back', questions_path, class: 'button right'

= render 'form'

app/views/questions/index.html.slim
h1.clearfix
  | All questions
  = link_to 'Add Question', new_question_path, class: 'button right'

= paginate @questions

table
  tr
    th
    th Body
    th Author
    th colspan=3
  = render @questions

app/views/questions/new.html.slim
h1
  | Create question
  = link_to 'Back', questions_path, class: 'button right'

= render 'form'

app/views/questions/show.html.slim
h1.clearfix
  | Question ##{@question.id}
  .right
    - if user_signed_in? && (@question.user == current_user)
      =' link_to 'Edit', edit_question_path(@question), class: 'button'
      =' link_to 'Delete', question_path(@question), method: :delete, data: {confirm: 'Sure?'}, class: 'button'
    = link_to 'Back', questions_path, class: 'button'

dl
  dt Body
  dd = @question.body
  dt Author
  dd = @question.author

h2 Add Answer

= render 'answers/form'

h2 Answers

table
  tr
    th
    th Body
    th Author
    th colspan=3
  = render @answers